baseURL: "https://bitground.de/"
languageCode: "en-us"
title: "bitground"
theme: "papermod"

disableKinds:
- taxonomy
- term
- rss

params:
  defaultTheme: auto # to switch between dark or light according to browser theme

  profileMode:
    enabled: true
    title: "bitground" # optional default will be site title
    subtitle: "home of bits and bytes..."
    #imageUrl: "<image link>" # optional
    #imageTitle: "<title of image as alt>" # optional
    #imageWidth: 120 # custom size
    #imageHeight: 120 # custom size
    buttons:
    # - name: Github
    #   url: "https://github.com/"

  socialIcons: # optional
  - name: "github"
    url: "https://github.com/cybrwshl"
